export const timeline = [
  {
    id: 1,
    year: 'College Days',
    title: 'The Beginning of Friendship',
    emoji: '🎓',
    description: 'We met in SVCE college as classmates and friends. Those early days were filled with lectures, assignments, and endless conversations.',
    color: 'from-blue-400 to-cyan-500',
    bgImage: '/assets/Srii2.jpeg',
  },
  {
    id: 2,
    year: 'Friendship Deepens',
    title: 'Best Friends Forever',
    emoji: '🤝',
    description: 'Our friendship grew stronger with each passing day. Study sessions, college events, late-night talks - we became each other\'s confidants.',
    color: 'from-purple-400 to-pink-500',
    bgImage: '/assets/Srii4.jpeg',
  },
  {
    id: 3,
    year: 'The Realization',
    title: 'When Friendship Became Love',
    emoji: '💕',
    description: 'Somewhere along the way, we realized our feelings were deeper than friendship. The way we cared for each other - it was love.',
    color: 'from-rose-400 to-pink-500',
    bgImage: '/assets/Srii8.jpeg',
  },
  {
    id: 4,
    year: 'Graduation',
    title: 'Starting Our Careers',
    emoji: '🎓',
    description: 'We graduated and started our professional journeys at different companies. Even though we were apart during work hours, our bond only grew stronger.',
    color: 'from-indigo-400 to-purple-500',
    bgImage: '/assets/Srii5.jpeg',
  },
  {
    id: 5,
    year: 'Present',
    title: 'Building Our Future Together',
    emoji: '💼',
    description: 'Today, we\'re both working professionals, building our careers while planning our future together. Every day is a step closer to our dream.',
    color: 'from-teal-400 to-cyan-500',
    bgImage: '/assets/Srii6.jpeg',
  },
  {
    id: 6,
    year: 'Always',
    title: 'Every Outing is a Date',
    emoji: '🚗',
    description: 'Every time we go out, it feels so special—every outing with you always feels like a date.',
    color: 'from-orange-400 to-pink-500',
    bgImage: '/assets/Srii23.jpeg',
  },
]

export const memories = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    title: 'College Days',
    date: 'SVCE College Memories',
    description: 'Those beautiful college days when we were just friends, studying together, sharing notes, and building our friendship.',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
    title: 'Study Sessions',
    date: 'Late night studies',
    description: 'Countless study sessions together, helping each other with assignments and projects. Those moments brought us closer.',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    title: 'College Events',
    date: 'Festivals & celebrations',
    description: 'College festivals, events, and celebrations - we experienced them all together, creating memories that last forever.',
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&q=80',
    title: 'Graduation Day',
    date: 'Our big day',
    description: 'Graduating together, starting our professional journeys. We were ready to take on the world, together.',
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    title: 'Working Life',
    date: 'Building careers',
    description: 'Now we\'re both working professionals at different companies, but our love keeps us connected every single day.',
  },
  {
    id: 6,
    image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=80',
    title: 'Future Together',
    date: 'Our future',
    description: 'Looking forward to all the beautiful moments we\'ll share together as we continue our journey.',
  },
]

export const reasons = [
  {
    id: 1,
    title: 'Your Care',
    emoji: '🤗',
    reason: 'From our days at SVCE, your care has been my constant. You started as a best friend, but your caring nature laid the foundation for our beautiful love.',
    color: 'from-blue-400 to-cyan-500',
    video: '/assets/Video8.mp4',
    image: '/assets/Srii10.jpeg',
  },
  {
    id: 2,
    title: 'Study Partner',
    emoji: '📚',
    reason: "I didn't know anything about coding or development, but you inspired and helped me learn. I'm here today only because of you all the credit goes to you for my growth!",
    color: 'from-purple-400 to-pink-500',
    video: '/assets/Video10.mp4',
    image: '/assets/Srii19.jpeg',
  },
  {
    id: 3,
    title: 'Dream Fulfiller',
    emoji: '✈️',
    reason: 'You fulfill all my dreams! Taking me on my first flight with you was incredibly special. You understand me like no one else and make every dream come true.',
    color: 'from-rose-400 to-pink-500',
    video: '/assets/Video11.mp4',
    image: '/assets/Srii18.jpeg',
  },
  {
    id: 4,
    title: 'Your Ambition',
    emoji: '💼',
    reason: 'I love how driven you are in your career. Watching you grow professionally while we plan our future together is amazing.',
    color: 'from-indigo-400 to-purple-500',
    video: '/assets/Video14.mp4',
    image: '/assets/Srii9.jpeg',
  },
  {
    id: 5,
    title: 'Your Support',
    emoji: '🤝',
    reason: 'Even though we work at different companies, you always support my career and dreams. That means everything.',
    color: 'from-green-400 to-teal-500',
    video: '/assets/Video13.mp4',
    image: '/assets/Srii16.jpeg',
  },
  {
    id: 6,
    title: 'My Pillar of Strength',
    emoji: '💪',
    reason: 'When I struggled with my weight, you never discouraged me. You motivated me to hit the gym, helping me lose 20kgs. The respect and confidence I have now is all because of your incredible support.',
    color: 'from-orange-400 to-red-500',
    video: '/assets/Video12.mp4',
    image: '/assets/Srii20.jpeg',
  },
]

export const reels = [
  {
    id: 1,
    src: '/assets/Video1.mp4',
    title: 'Birthday Celebration',
    description: 'An unforgettable birthday! You celebrated grandly, making me feel so special. A memory I\'ll cherish forever.',
  },
 {
    id: 2,
    src: '/assets/Video9.mp4',
    title: 'Your care',
    description: 'Whenever I feel alone, you are always there for me. You care for me in a way that I will cherish forever.',
  },
  {
    id: 3,
    src: '/assets/Video3.mp4',
    title: 'A Special Dedication',
    description: 'I made this special video just for you because I love you more than anything. You mean everything to me!',
  },
  {
    id: 4,
    src: '/assets/Video4.mp4',
    title: 'First Car Drive',
    description: 'Our first car drive together! That moment with you is a memory I will cherish forever.',
  },
{
    id: 5,
    src: '/assets/Video6.mp4',
    title: 'First Internship at ThinkJS',
    description: 'Our first job together during our 3-month internship. Unforgettable office memories that marked the beginning of our careers.',
  },
  {
    id: 6,
    src: '/assets/Video5.mp4',
    title: 'ISKCON Temple Visit',
    description: 'Our first visit to the ISKCON temple together. A peaceful and spiritual memory that I hold close to my heart.',
  },
   {
    id: 7,
    src: '/assets/Video7.mp4',
    title: 'Date at Glen\'s Bakehouse',
    description: 'Our sweet date at Glen\'s Bakehouse. Sharing good food and great conversation, creating unforgettable memories together.',
  },
]
